/** 独立临时数据库；不连接 12306，不发送外部通知。 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'my12306-features-'));
process.env.MY12306_DATA_DIR = dir;
process.env.MY12306_MULTI_USER = '1';
process.env.MY12306_ADMIN_USER = 'testadmin';
process.env.MY12306_ADMIN_PASSWORD = 'TestOnly-Admin-12345';
const { default: Fastify } = await import('fastify');
const { applySchema, seedAdmin, getDb, closeDb } = await import('../db/index.js');
const { registerAuth } = await import('../routes/auth.routes.js');
const { planRoutes } = await import('../routes/plan.routes.js');
const { logRoutes } = await import('../routes/log.routes.js');
const { notificationRoutes } = await import('../routes/notification.routes.js');
const { listChannels, migrateNotifications, deliver, buildMessage, isPublicIPv4, validateConfig, publicChannel } = await import('../notify/channels.js');
const { fmtCn } = await import('../../../web/src/utils/time.js');
const { socketRoutes } = await import('../ws/routes.js');
const { default: websocket } = await import('@fastify/websocket');
const { wsHub } = await import('../ws/hub.js');
const { Logger, setLogHub } = await import('../logger.js');
const { UsersRepo, PassengersRepo, PlansRepo, TasksRepo, FeishuRepo, userCanRun } = await import('../db/repo.js');
let count = 0;
function check(condition: unknown, message: string) { assert.ok(condition, message); console.log('✓ ' + message); count++; }
applySchema(); seedAdmin();
FeishuRepo.upsert('system','https://open.feishu.cn/hook/legacy','LEGACY_FAKE_SECRET',true,'Legacy');
migrateNotifications();
const app = Fastify(); registerAuth(app); await app.register(websocket); await app.register(socketRoutes); setLogHub(wsHub); await app.register(planRoutes); await app.register(logRoutes); await app.register(notificationRoutes);
const login = async (username: string, password: string) => { const r=await app.inject({ method:'POST', url:'/api/auth/login', payload:{ username,password } }); assert.equal(r.statusCode,200,r.body); return String(r.headers['set-cookie']).split(';')[0]; };
try {
  check(listChannels('system').length === 1 && listChannels('system')[0].config.secret === 'LEGACY_FAKE_SECRET', '旧飞书配置及签名密钥迁移');
  check(fmtCn('2026-09-22 12:00:00') === '2026-09-22 20:00:00', 'SQLite UTC 时间正确显示为北京时间');
  check(fmtCn('2026-09-22T12:00:00Z') === '2026-09-22 20:00:00', 'ISO 时间与 SQLite 时间显示一致');
  check((await app.inject('/api/plans')).statusCode===401,'匿名请求无法读取计划');
  const admin = await login('testadmin','TestOnly-Admin-12345');
  check(admin.startsWith('my12306_session='),'登录建立 HttpOnly 会话');
  const create=await app.inject({ method:'POST',url:'/api/admin/users',headers:{cookie:admin},payload:{username:'alice',password:'TestOnly-Alice-12345',role:'user',displayName:'Alice'} });
  check(create.statusCode===200,'管理员创建用户'); const alice=create.json();
  const other=UsersRepo.create('bob', 'unused', 'user', 'Bob');
  const cookie=await login('alice','TestOnly-Alice-12345');
  await assert.rejects(app.injectWS('/ws'), /401/); count++; console.log('✓ WebSocket 拒绝匿名握手');
  const wsAdmin = await app.injectWS('/ws', {headers:{cookie:admin}});
  const wsAlice = await app.injectWS('/ws', {headers:{cookie}});
  const seenAdmin: string[] = [], seenAlice: string[] = [];
  wsAdmin.on('message', data => seenAdmin.push(String(data)));
  wsAlice.on('message', data => seenAlice.push(String(data)));
  const aliceMessage = new Promise<void>(resolve => wsAlice.once('message',()=>resolve()));
  wsHub.broadcastToUser(alice.id,{type:'task',payload:'ALICE_ONLY'}); await aliceMessage;
  const adminMessage = new Promise<void>(resolve => wsAdmin.once('message',()=>resolve()));
  wsHub.broadcastToUser('system',{type:'task',payload:'ADMIN_ONLY'}); await adminMessage;
  check(!seenAdmin.some(s=>s.includes('ALICE_ONLY')) && !seenAlice.some(s=>s.includes('ADMIN_ONLY')), 'WebSocket 任务推送按用户隔离');
  wsAdmin.terminate(); wsAlice.terminate();
  check((await app.inject({url:'/api/admin/users',headers:{cookie}})).statusCode===403,'普通用户无法使用管理员接口');
  check((await app.inject({method:'POST',url:'/api/plans',headers:{cookie,origin:'https://evil.example'},payload:{}})).statusCode===403,'拒绝跨站写操作');
  const p=PassengersRepo.upsert(other.id,{name:'BobOnly',idNo:'TEST_BOB_ONLY',idTypeCode:'1',phone:null,source:'manual',passengerType:'成人'});
  check((await app.inject({url:'/api/passengers',headers:{cookie}})).json().length===0,'乘车人列表按用户隔离');
  check((await app.inject({method:'DELETE',url:`/api/passengers/${p.id}`,headers:{cookie}})).statusCode===404,'不能删除其他用户乘车人');
  check((await app.inject({method:'POST',url:'/api/passengers',headers:{cookie},payload:{id:p.id,name:'Changed',idNo:'123456789012345678',idTypeCode:'1',passengerType:'成人'}})).statusCode===404,'不能修改其他用户乘车人');
  new Logger('test',alice.id).info('Alice process', {secret:'NEVER_EXPORT_SECRET',idNo:'123456789012345678',url:'https://example.com/private'});
  new Logger('test',other.id).info('Bob private');
  let logs=(await app.inject({url:`/api/logs?userId=${other.id}`,headers:{cookie}})).json();
  check(logs.items.some((r: any) => r.message==='Alice process') && logs.items.every((r: any) => r.user_id===alice.id),'伪造 userId 不会越权查询日志');
  check(!JSON.stringify(logs).includes('NEVER_EXPORT_SECRET'),'查询日志隐藏敏感字段');
  getDb().prepare('INSERT INTO logs (id,user_id,level,category,message,detail) VALUES (?,?,?,?,?,?)').run('legacy-log',alice.id,'info','legacy','=SUM(1,1)',JSON.stringify({secret:'LEGACY_PRIVATE_SECRET',url:'https://example.com/private'}));
  const oldExport=await app.inject({url:'/api/logs/export?keyword=SUM',headers:{cookie}});
  check(oldExport.body.includes("'=SUM") && !oldExport.body.includes('LEGACY_PRIVATE_SECRET'),'导出旧日志仍脱敏并转义 CSV 公式');
  const paged=(await app.inject({url:'/api/logs?pageSize=1&page=1',headers:{cookie}})).json();
  const paged2=(await app.inject({url:'/api/logs?pageSize=1&page=2',headers:{cookie}})).json();
  check(paged.items.length===1 && paged2.items.length===1 && paged.items[0].id!==paged2.items[0].id,'日志分页不重复首条记录');
  check((await app.inject({url:'/api/logs?from=2099-01-01T00:00:00Z',headers:{cookie}})).json().total===0,'日志时间范围筛选');
  const csv=await app.inject({url:'/api/logs/export',headers:{cookie}});
  check(csv.statusCode===200 && csv.headers['content-disposition']?.includes('.csv') && !csv.body.includes('Bob private'),'CSV 导出按用户隔离');
  check((await app.inject({url:'/api/logs?page=-1',headers:{cookie}})).statusCode===400,'日志分页参数验证');
  check((await app.inject({url:'/api/logs?keyword=nomatch',headers:{cookie}})).json().total===0,'日志关键词筛选生效');
  check((await app.inject({url:'/api/logs',headers:{cookie:admin}})).json().total>=2,'管理员可查询所有过程日志');
  const channel=await app.inject({method:'POST',url:'/api/notifications',headers:{cookie},payload:{name:'Mock',type:'feishu',enabled:true,events:['order_success'],config:{webhookUrl:'https://open.feishu.cn/open-apis/bot/v2/hook/mock',secret:'FAKE_SIGNING_SECRET'}}});
  check(channel.statusCode===200,'保存通知通道'); const ch=channel.json();
  check(!channel.body.includes('FAKE_SIGNING_SECRET') && !channel.body.includes('/hook/mock'),'通知配置不回显密钥及完整 Webhook');
  const patch=await app.inject({method:'POST',url:'/api/notifications',headers:{cookie},payload:{id:ch.id,name:'Renamed',type:'feishu',enabled:false,events:['order_success'],config:{secret:''}}});
  check(patch.statusCode===200 && listChannels(alice.id)[0].config.secret==='FAKE_SIGNING_SECRET','编辑留空保留原密钥');
  check((await app.inject({url:'/api/notifications',headers:{cookie:admin}})).json().every((c: any) => c.id !== ch.id),'通知通道按用户隔离');
  check((await app.inject({method:'DELETE',url:`/api/notifications/${ch.id}`,headers:{cookie:admin}})).statusCode===404,'其他用户无法删除通知通道');
  const base=listChannels(alice.id)[0];
  for(const type of ['feishu','wecom','dingtalk','telegram','webhook'] as const) {
    const urls={feishu:'https://open.feishu.cn/hook/mock',wecom:'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=mock',dingtalk:'https://oapi.dingtalk.com/robot/send?access_token=mock',telegram:'',webhook:'https://example.com/hook'};
    const c={...base,type,config:{webhookUrl:urls[type],secret:'test',botToken:'123:FAKE_TEST_TOKEN',chatId:'-123'}};
    const good=await deliver(c,'Test message','test',false,async request => { const text=JSON.stringify(request.body); assert.ok(text.includes('Test message')); return { status:200,data: type==='feishu'?{code:0}:type==='telegram'?{ok:true}:{errcode:0} }; });
    check(good.ok,`${type} 适配器发送与成功解析`);
    const bad=await deliver(c,'Test message','test',false,async () => ({status: type==='webhook'?500:200,data:{code:19021,errcode:1,ok:false}}));
    check(!bad.ok,`${type} 不将平台拒绝误判为成功`);
  }
  const ding=buildMessage({...base,type:'dingtalk',config:{webhookUrl:'https://oapi.dingtalk.com/robot/send?access_token=mock',secret:'secret'}},'text','test',1000);
  check(new URL(ding.url).searchParams.has('sign'),'钉钉签名附加到查询参数');
  check(!isPublicIPv4('127.0.0.1') && !isPublicIPv4('192.168.1.1') && !isPublicIPv4('169.254.169.254') && isPublicIPv4('8.8.8.8'),'Webhook 拒绝本机与私网地址');
  assert.throws(()=>validateConfig('feishu',{webhookUrl:'https://evil.example/hook'})); count++;
  check((await app.inject({method:'PATCH',url:'/api/admin/users/system',headers:{cookie:admin},payload:{disabled:true}})).statusCode===400,'不能停用当前管理员');
  getDb().prepare("INSERT INTO plans (id,user_id,name,status,from_station,to_station,date_mode,travel_date,valid_from,passenger_ids) VALUES ('alice-plan',?,'AlicePlan','active','A','B','single','2099-01-01','2026-01-01','[]')").run(alice.id);
  const scheduled=TasksRepo.create({userId:alice.id,planId:'alice-plan',planDateId:null,travelDate:'2099-01-01',trainNumber:null,saleAt:'2020-01-01T00:00:00Z',status:'queried'});
  check(PlansRepo.listActive().some(p=>p.id==='alice-plan') && TasksRepo.listDue(new Date().toISOString()).some(t=>t.id===scheduled.id),'启用用户的计划正常进入调度候选');
  const disabled=await app.inject({method:'PATCH',url:`/api/admin/users/${alice.id}`,headers:{cookie:admin},payload:{disabled:true}});
  check(!PlansRepo.listActive().some(p=>p.id==='alice-plan') && !TasksRepo.listDue(new Date().toISOString()).some(t=>t.id===scheduled.id), '停用用户的计划和任务被查询层排除');
  check(disabled.statusCode===200 && !userCanRun(alice.id),'停用用户后停止调度资格');
  check((await app.inject({url:'/api/passengers',headers:{cookie}})).statusCode===401,'停用账号撤销现有登录');
  applySchema(); seedAdmin(); migrateNotifications();
  check(!!UsersRepo.findById(other.id) && PassengersRepo.list(other.id).length===1,'重启迁移保留其他用户及数据');
  check(listChannels(alice.id).length===1,'通知迁移幂等，不重复创建通道');
  getDb().prepare("DELETE FROM notification_channels WHERE user_id = 'system'").run(); migrateNotifications();
  check(listChannels('system').length===0,'删除迁移后的通道不会在重启时复活');
  getDb().prepare("INSERT INTO plans (id,user_id,name,status,from_station,to_station,date_mode,travel_date,valid_from,passenger_ids) VALUES ('bob-plan',?,'BobPlan','active','A','B','single','2099-01-01','2026-01-01','[]')").run(other.id);
  TasksRepo.create({userId:other.id,planId:'bob-plan',planDateId:null,travelDate:'2099-01-01',trainNumber:null,saleAt:'2020-01-01T00:00:00Z',status:'queried'});
  const single=spawnSync(process.execPath,['--import','tsx','--input-type=module','-e', `
    import assert from 'node:assert/strict';
    import { applySchema, seedAdmin, closeDb } from './server/src/db/index.ts';
    import { UsersRepo, PlansRepo, TasksRepo } from './server/src/db/repo.ts';
    applySchema(); seedAdmin();
    assert.ok(UsersRepo.findById(${JSON.stringify(other.id)}));
    assert.ok(!PlansRepo.listActive().some(p=>p.id==='bob-plan'));
    assert.ok(!TasksRepo.listDue(new Date().toISOString()).some(t=>t.planId==='bob-plan'));
    closeDb();
  `],{encoding:'utf8',env:{...process.env,MY12306_MULTI_USER:'0'}});
  check(single.status===0,'切换单用户模式保留其他账号数据但不调度其任务：'+(single.status===0?'通过':single.stderr));
  const reset=await app.inject({method:'PATCH',url:`/api/admin/users/${alice.id}`,headers:{cookie:admin},payload:{disabled:false,password:'TestOnly-NewPassword-12345'}});
  check(reset.statusCode===200,'管理员重新启用账号并重置密码');
  const freshCookie=await login('alice','TestOnly-NewPassword-12345');
  const changed=await app.inject({method:'POST',url:'/api/auth/password',headers:{cookie:freshCookie},payload:{oldPassword:'TestOnly-NewPassword-12345',password:'TestOnly-FinalPassword-12345'}});
  check(changed.statusCode===200 && (await app.inject({url:'/api/auth/me',headers:{cookie:freshCookie}})).statusCode===401,'修改密码立即撤销旧会话');
  const expiredCookie=await login('alice','TestOnly-FinalPassword-12345');
  getDb().prepare('UPDATE auth_sessions SET expires_at = 1 WHERE user_id = ?').run(alice.id);
  check((await app.inject({url:'/api/auth/me',headers:{cookie:expiredCookie}})).statusCode===401,'过期会话不能继续读取数据');
  await app.inject({method:'POST',url:'/api/auth/logout',headers:{cookie:admin}});
  check((await app.inject({url:'/api/auth/me',headers:{cookie:admin}})).statusCode===401,'退出管理台撤销服务端会话');
  for(let i=0;i<10;i++) await app.inject({method:'POST',url:'/api/auth/login',payload:{username:'invalid',password:'invalid'}});
  check((await app.inject({method:'POST',url:'/api/auth/login',payload:{username:'invalid',password:'invalid'}})).statusCode===429,'连续错误登录受到限流');
  console.log(`\n${count} feature checks passed.`);
} finally { await app.close(); closeDb(); fs.rmSync(dir,{recursive:true,force:true}); }
